### ISSUE TITLE
Backend Product Searches Not Working

### ISSUE THREAD

**Issue by TimbreDesign** [10up/elasticpress-woocommerce#11]
Experiencing backend product searches not returning any queries. Screenshot of test site search "Ninja" with WC dummy data.

![screenshot 2016-02-25 01 51 33](https://cloud.githubusercontent.com/assets/13074081/13295138/5c7fda74-db62-11e5-9df4-9e436095ef9e.png)

**Comment by tlovett1** [comment]
Did you reindex after activating this plugin?

**Comment by TimbreDesign** [comment]
As far as I'm aware, yes. All product searches on the frontend work well. Will try reindexing again though and see if that fixes it.

**Comment by tlovett1** [comment]
Should be fixed in 1.1

**Comment by TimbreDesign** [comment]
Ah ok, do I need to reindex again after updating? I just updated to 1.1, seems I'm now getting this error:
![screenshot 2016-02-25 15 58 00](https://cloud.githubusercontent.com/assets/13074081/13313449/f05e4296-dbd8-11e5-900c-cb24ab8dbdd2.png)

**Comment by tlovett1** [comment]
That warning is fixed in 1.1.1. Sorry!

**Comment by TimbreDesign** [comment]
No worries Taylor, what you are doing is most excellent, your time and effort is appreciated!
