### ISSUE TITLE
Include custom post statuses when indexing

### ISSUE THREAD

**Issue by alchemistgm** [10up/elasticpress-woocommerce#13]
This may already be working correctly - but because we create custom post statuses (for example to hold an international order until manual verification can take place) - I wanted to double check that custom post statuses that get created in functions.php will get included in any indexing.

we use:
add_filter( 'wc_order_statuses', 'add_holding_intl_shipping_to_order_statuses' );
in functions.php

**Comment by tlovett1** [comment]
Can you post all the relevant code please?

**Comment by alchemistgm** [comment]
``` php
function add_holding_intl_shipping_to_order_statuses( $order_statuses ) {
    $new_order_statuses = array();
    // add new order status after processing
    foreach ( $order_statuses as $key => $status ) {
        $new_order_statuses[ $key ] = $status;
        if ( 'wc-processing' === $key ) {
            $new_order_statuses['wc-hold-intl-ship'] = 'Holding Intl Shipment';
            $new_order_statuses['wc-hold-doubledip'] = 'Holding Multiple FCO';
            $new_order_statuses['wc-waiting-upsell'] = 'Waiting for Upsell';
        }
    }
    return $new_order_statuses;
}
add_filter( 'wc_order_statuses', 'add_holding_intl_shipping_to_order_statuses' );
```

**Comment by tlovett1** [comment]
Ok, you're right we may need to address. I'll take a look. Thanks!
