### ISSUE TITLE
wc-api calls fail returning "invalid order"

### ISSUE THREAD

**Issue by alchemistgm** [10up/elasticpress-woocommerce#14]
An external wc-api call (such as a fulfillment house pulling orders or posting tracking numbers, or a call from a service like taxjar to pick up tax data) will fail with the elasticpress-woocommerce plugin activated.

example usage:
URL/wc-api/v2/orders?filter[meta]=true&fields=order_meta.customer_status&filter[limit]=200&page=1&consumer_key=ck_XXXXXXXXXX&consumer_secret=cs_XXXXXXXXX
(must supply valid keys for specific woocommerce install)

**Comment by alchemistgm** [comment]
A workaround for this I have used is to check for wc-api in the url and selectively load the elasticpress-woocommerce plugin functionality:

$url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
if (strpos($url,'wc-api') === false) {
    include 'ep-wc-include.php';
}

this should work as long as the api is reading only, and an update to the elasticpress index is not required

**Comment by tlovett1** [comment]
What is the error message you are seeing?

**Comment by alchemistgm** [comment]
"invalid order"

normal:
<img width="543" alt="2016-05-05_2142" src="https://cloud.githubusercontent.com/assets/12636431/15064612/162655b8-130b-11e6-9d80-f9817a7e46b4.png">

with elasticpress-woocommerce 1.2:
<img width="1278" alt="2016-05-05_2152" src="https://cloud.githubusercontent.com/assets/12636431/15064689/0b8b70c4-130c-11e6-8564-cbebf51b813e.png">

**Comment by tlovett1** [comment]
Got it. We'll have a bug fix out shortly.

**Comment by spectodesign** [comment]
What is the plugin version containing this fix please?
