### ISSUE TITLE
Search in WooCommerce orders page not working via ElasticSearch

### ISSUE THREAD

**Issue by pandjarov** [10up/elasticpress-woocommerce#16]
I have a website I am trying to setup with the plugin with 80k orders, each having 50 entries in the postmeta table resulting in 4mil rows there. The server is running HHVM with Redis on an Apache with NGINX infront of it for caching. Everything is working perfectly except for the WordPress connection with the ElasticSearch service.

The front end search is working as supposed and perfeclty fast. 

The backend search, however, doesn't behave correctly. A search in the orders page takes like 1 minute. I checked the query and can't even find the term I am looking for in it so it seems that there's definitelly something wrong. Any idea what could it be? Here's the query:

{
    "from": 0,
    "size": 20,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": []
    },
    "filter": {
        "and": [
            {
                "term": {
                    "post_type.raw": "shop_order"
                }
            },
            {
                "terms": {
                    "post_status": [
                        "publish",
                        "future",
                        "draft",
                        "pending",
                        "private",
                        "inherit",
                        "in-progress",
                        "failed",
                        "wc-pending",
                        "wc-processing",
                        "wc-on-hold",
                        "wc-completed",
                        "wc-cancelled",
                        "wc-refunded",
                        "wc-failed",
                        "wc-partialrefund425",
                        "fue-inactive",
                        "fue-active",
                        "fue-archived"
                    ]
                }
            }
        ]
    }
# }

{
    "from": 0,
    "size": 10,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": []
    },
    "filter": {
        "and": [
            {
                "bool": {
                    "must": [
                        {
                            "terms": {
                                "meta._wc_customer_order_csv_export_is_exported.raw": [
                                    0
                                ]
                            }
                        }
                    ]
                }
            },
            {
                "term": {
                    "post_type.raw": "shop_order"
                }
            },
            {
                "terms": {
                    "post_status": [
                        "publish",
                        "future",
                        "draft",
                        "pending",
                        "private",
                        "inherit",
                        "in-progress",
                        "failed",
                        "wc-pending",
                        "wc-processing",
                        "wc-on-hold",
                        "wc-completed",
                        "wc-cancelled",
                        "wc-refunded",
                        "wc-failed",
                        "wc-partialrefund425",
                        "fue-inactive",
                        "fue-active",
                        "fue-archived"
                    ]
                }
            }
        ]
    }
# }

{
    "from": 0,
    "size": 10,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": []
    },
    "filter": {
        "and": [
            {
                "bool": {
                    "must": [
                        {
                            "terms": {
                                "meta._wc_customer_order_csv_export_is_exported.raw": [
                                    1
                                ]
                            }
                        }
                    ]
                }
            },
            {
                "term": {
                    "post_type.raw": "shop_order"
                }
            },
            {
                "terms": {
                    "post_status": [
                        "publish",
                        "future",
                        "draft",
                        "pending",
                        "private",
                        "inherit",
                        "in-progress",
                        "failed",
                        "wc-pending",
                        "wc-processing",
                        "wc-on-hold",
                        "wc-completed",
                        "wc-cancelled",
                        "wc-refunded",
                        "wc-failed",
                        "wc-partialrefund425",
                        "fue-inactive",
                        "fue-active",
                        "fue-archived"
                    ]
                }
            }
        ]
    }
}

If you want, we can talk over Slack, and I can give you every piece of information regarding the setup, configuration, etc.

**Comment by tlovett1** [comment]
Should be mostly fixed in 1.1.3. Note WooCommerce has a filter in their master branch that makes this possible. This filter has not been released in a version yet.
