### ISSUE TITLE
Adding orders manually shows error "loading failed" when adding line items

### ISSUE THREAD

**Issue by alchemistgm** [10up/elasticpress-woocommerce#18]
From orders, add order, then add line item and it pulls up a box to type the first 3 letters or more of a product to add to the order. 

With elasticpress-woocommerce plugin enabled, after a short delay this just populates with an error in red saying "loading failed", but after turning off elasticpress-woocommerce then typing any three letters from a product name will bring up a suggested list of products to select from.

**Comment by joshuaabenazer** [comment]
@alchemistgm Not able to reproduce this issue. Can you confirm if you are still facing this issue with the latest version of ElasticPress WooCommerce?

**Comment by alchemistgm** [comment]
This was my error, it had not been indexed when I got this error.
