### ISSUE TITLE
Server 500 Error

### ISSUE THREAD

**Issue by emendesign** [10up/elasticpress-woocommerce#19]
We just setup elasticpress and elasticpress woocommerce on a site and it seems to be working great except for the full shop view. It seems like it is based around the total products included within the category or tag that causes the server 500 error. For example a category or tag with 50 items loads fine. However a category or tag with 2000 products does not.

Have you seen this before?

**Comment by joshuaabenazer** [comment]
@emendesign could you check your logs to see if it can provide more context as to what exactly could be causing this issue? Does this happen with ElasticPress WooCommerce deactivated?

**Comment by emendesign** [comment]
I will look on the logs but the issue does not exist when ElasticPress
WooCommerce is deactivated.

On Mon, Mar 21, 2016 at 6:10 AM, Joshua Abenazer notifications@github.com
wrote:

> @emendesign https://github.com/emendesign could you check your logs to
> see if it can provide more context as to what exactly could be causing this
> issue? Does this happen with ElasticPress WooCommerce deactivated?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/10up/elasticpress-woocommerce/issues/19#issuecomment-199228141

## 

Neil Moeller
EM EN Design
http://www.emendesign.com
507-218-2453

**Comment by tlovett1** [comment]
We will need to see the error in the logs to help.
