### ISSUE TITLE
Live Searches

### ISSUE THREAD

**Issue by andrewgoodnz** [10up/elasticpress-woocommerce#20]
Hi, 

Will this integrate directly into any of the Live Search plugins out there?

**Comment by tlovett1** [comment]
Can you provide an example of one of those plugins? Thanks!

**Comment by andrewgoodnz** [comment]
Sorry, missed notification coming through.

Examples:
https://wordpress.org/plugins/woocommerce-predictive-search/
https://wordpress.org/plugins/yith-woocommerce-ajax-search/screenshots/
http://codecanyon.net/item/woocommerce-live-product-search/5211796

**Comment by tlovett1** [comment]
Right now we haven't tested against any of those plugins. I'd love to hear how they work for you.

**Comment by andrewgoodnz** [comment]
What is the best to tell if data is coming from ElasticPress or direct from
database?
