### ISSUE TITLE
not indexing shop orders

### ISSUE THREAD

**Issue by alchemistgm** [10up/elasticpress-woocommerce#21]
When I index with elasticpress-woocommerce  plugin version 1.1.1 to re-index it indexes all 123,000 shop_orders - but 1.1.3 only indexes 61 pages and posts, it does not index shop_orders. What might I be missing? It finished quickly and says it's successful, but of course it can't find any orders in admin until I revert to 1.1.1 and re-index...
I'm using wp-cli "wp elasticpress index --setup"

**Comment by tlovett1** [comment]
Are you sure the plugin is active?

**Comment by tlovett1** [comment]
Testing locally....

**Comment by tlovett1** [comment]
@alchemistgm is this locally or on a remote server?

**Comment by alchemistgm** [comment]
On a remote server - if it sounds like it's not active to you I will try it again tonight in the wee hours where I can't screw up live traffic, and make sure it's active. Pretty sure it was... but can test for that.
Oh! I see there's a shiny new 1.1.4 -- I'll test with that!

**Comment by alchemistgm** [comment]
feeling silly - that was it
