### ISSUE TITLE
sku and tag support

### ISSUE THREAD

**Issue by kimryuhyun** [10up/elasticpress-woocommerce#22]
Hi,

It seems like it doesn't currently search either sku or product tags. Am I correct?

If not, how do you enable this?

Thx. Ryan

**Comment by tlovett1** [comment]
On the front end or the backend?

**Comment by tlovett1** [comment]
Added in 1.2

**Comment by kimryuhyun** [comment]
On the Frontend. 

나의 iPhone에서 보냄
1. 5. 6. 오전 3:04 Taylor Lovett notifications@github.com 작성:
