### ISSUE TITLE
No demo ? 

### ISSUE THREAD

**Issue by go6media** [10up/elasticpress-woocommerce#23]
Sorry, but i cant find anywhere else to post this as you've said you wont monitor the plug in page

so you have an example of this running on a woo site please?

**Comment by tlovett1** [comment]
Right now we have none :( It would be great to have one in the future.

**Comment by BurlesonBrad** [comment]
@tlovett1 I'll volunteer a URL running Woo, php7, WC Nightly Betas, WooCommerce Beta, _amongst other things_ 

https://bradgriffin.me/contact-brad-griffin
