### ISSUE TITLE
woocommerce product category page return nothing

### ISSUE THREAD

**Issue by jasonhoi** [10up/elasticpress-woocommerce#3]
Hi, first thanks for the good work, but I find a bug on the woocommerce product category page, where I have multiple level of product category tree, like:
top-cat1 > cat001
top-cat1 > cat002, 
top-cat2 > cat003, 
top-cat3
When there are products only belongs to cat001, but directly belong to top-cat1, usually, by default, when I access the top-cat1 product category page I should see all products inside both top-cat1, cat001 and cat002.

**Comment by tlovett1** [comment]
@joshuaabenazer is this fixed? If so, please close.

**Comment by joshuaabenazer** [comment]
@tlovett working on a fix for this.
